### ISSUE TITLE
Why do I always encounter the error: 'ValueError: Imaginary component 89928690.58258057'

### ISSUE THREAD

**Issue by BlackAngel-511** [bioinf-jku/TTUR#31]
I use the fid.py to measure fid score of my images datasets, I generated 10000 images in tImages directory and used the command 'python fid.py ./tImages fid_stats_celeba.npz' or 'python fid.py ./tImages ./sImages ' (sImages directory is another images datasets), but waiting a while, I always get a ValueError. e.g. 'ValueError: Imaginary component 89928690.58258057' or
'ValueError: Imaginary component 1.376687186290827e+24'. I don't know which step I did wrong. Could anyone tell me what the problem is, thanks!

error information:
Traceback (most recent call last):
File "fid.py", line 334, in
fid_value = calculate_fid_given_paths(args.path, args.inception, low_profile=args.lowprofile)
File "fid.py", line 317, in calculate_fid_given_paths
fid_value = calculate_frechet_distance(m1, s1, m2, s2)
File "fid.py", line 155, in calculate_frechet_distance
raise ValueError("Imaginary component {}".format(m))
ValueError: Imaginary component 1.376687186290827e+24

**Comment by mmderakhshani** [comment]
@BlackAngel-511. I received the same error. Were you able to solve this error? My command was:

```
python fid.py ../stage2/ ../fid_stats_celeba.npz --gpu 0
```

**Comment by mhex** [comment]
Could you pls post the min/max/mean values of both sigma1 and sigma2?

**Comment by mohammadhosseinashoori** [comment]
i have a same problem
my command:
!python '/content/fid.py' '/content/real_images_all/img' '/content/generated_images_all/img'

number of images: 8189 (same for real and generated directory)
error:
![error](https://user-images.githubusercontent.com/48843775/79909235-dfba1680-8431-11ea-827e-b798bd328619.png)


how to solve it?
thank you in advance

**Comment by BlackAngel-511** [comment]
I guess that the problem was caused by system environment. When  I recreate a new evironment in anconda, the problem magically disappeared.

**Comment by mohammadhosseinashoori** [comment]
@BlackAngel-511 
thank you for your comment
what is you tensorflow version?

thank you very much

**Comment by BlackAngel-511** [comment]
I trid to execute in tensorflow 1.11 or 1.14 and it worked

**Comment by mohammadhosseinashoori** [comment]
thank you i will try it

**Comment by mohammadhosseinashoori** [comment]
i create a new anaconda environment and install tensorflow version 1.14
it solved my problem
thank you

**Comment by mmderakhshani** [comment]
> i create a new anaconda environment and install tensorflow version 1.14
> it solved my problem
> thank you

Shall I ask your python version?

**Comment by mohammadhosseinashoori** [comment]
python 3.7.6

**Comment by mmderakhshani** [comment]
> python 3.7.6

I installed python=3.7.6 and tensorflow-gpu=1.14.0. But I received the same error. Could you please export your environment into .yml file and share it with me?

**Comment by mohammadhosseinashoori** [comment]
hello
i installed tensorflow 1.14.0 cpu not gpu, may be it is important ...
link of yml file:
[environment_tf_14.zip](https://github.com/bioinf-jku/TTUR/files/4564206/environment_tf_14.zip)

**Comment by ZejianLi** [comment]
Hello, I have the same error.The problem may not comes from the version of Tensorflow. It is from the code.

In https://github.com/bioinf-jku/TTUR/blob/master/fid.py#L88, `n_batches = n_images//batch_size` means the last batch is dropped, but in the next line `pred_arr = np.empty((n_images,2048))` keeps the places for the dropped samples and initializes them with arbitrary values. This seriously influences the final means and stds and causes the numerical error. 

It is even worse when the `np.empty()` gives zeros. In this case there wouldn't be any error but the final fid value would be slightly lower than the real one.

To fix this, we may rewrite `pred_arr = np.empty((n_batches*batch_size,2048))`.

**Comment by 3288103265** [comment]
The same question and  I cannot fix it with creating new environments.

**Comment by mhex** [comment]
should be fixed with last commit please test
